//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnouncementService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnnouncementService()
        {
            this.ExecutionService = new HashSet<ExecutionService>();
            this.HistoryCustomer = new HashSet<HistoryCustomer>();
            this.PhotoCompletedService = new HashSet<PhotoCompletedService>();
        }
    
        public int AnnouncementServiceId { get; set; }
        public string CustomerId { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public System.DateTime DateOfCompletion { get; set; }
        public Nullable<int> TermOfService { get; set; }
        public int CityId { get; set; }
        public string Description { get; set; }
        public int Place { get; set; }
        public int ServiceId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionService> ExecutionService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryCustomer> HistoryCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoCompletedService> PhotoCompletedService { get; set; }
        public virtual City City { get; set; }
        public virtual Service Service { get; set; }
        public virtual TypeOfPlace TypeOfPlace { get; set; }
    }
}
