//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExecutionService()
        {
            this.HistoryExecutor = new HashSet<HistoryExecutor>();
        }
    
        public int ExecutionServiceId { get; set; }
        public int AnnouncementServiceId { get; set; }
        public string ExecutorId { get; set; }
        public int StatusExecutionServiceId { get; set; }
    
        public virtual AnnouncementService AnnouncementService { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual StatusExecutionService StatusExecutionService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryExecutor> HistoryExecutor { get; set; }
    }
}
