//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryExecutor
    {
        public int ExecutionServiceId { get; set; }
        public string ExecutorId { get; set; }
        public string CustomerId { get; set; }
        public Nullable<byte> Rating { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ExecutionService ExecutionService { get; set; }
    }
}
