//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestForService
    {
        public int ServiceId { get; set; }
        public string CustomerId { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public System.DateTime DateOfCompletion { get; set; }
        public Nullable<int> TermOfService { get; set; }
        public int CityId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Place { get; set; }
        public Nullable<int> ServiceCategoryId { get; set; }
    
        public virtual City City { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual TypeOfPlace TypeOfPlace { get; set; }
    }
}
