//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCustomerExecutor
    {
        public int id { get; set; }
        public string CustomerId { get; set; }
        public string ExecutorId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string HaveCostStart { get; set; }
        public string HaveCost { get; set; }
        public string Period { get; set; }
        public string Position { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
